[package]
name = "nannou-generative-art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
lazy_static = "1.4.0"
nannou = "0.18.1"
rand = "0.8.5"
